export const studioSchemas = {
  Studio: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      name: { type: 'string' },
      slug: { type: 'string' },
      status: { type: 'string' },
      plan: { type: 'string' },
      logo_url: { type: 'string', nullable: true },
      logo_public_id: { type: 'string', nullable: true },
      contact_email: { type: 'string', format: 'email', nullable: true },
      contact_phone: { type: 'string', nullable: true },
      address: { type: 'string', nullable: true },
      social_links: {
        type: 'object',
        additionalProperties: { type: 'string' },
        nullable: true,
      },
    },
    required: ['id'],
  },
  StudioOnboardingRequest: {
    type: 'object',
    properties: {
      name: { type: 'string' },
      slug: { type: 'string' },
      logo_url: { type: 'string' },
      logo_public_id: { type: 'string' },
      clear_logo: { type: 'boolean' },
      contact_email: { type: 'string', format: 'email' },
      contact_phone: { type: 'string' },
      address: { type: 'string' },
      social_links: {
        type: 'object',
        additionalProperties: { type: 'string' },
      },
    },
    required: ['name'],
  },
  StudioPublic: {
    type: 'object',
    properties: {
      name: { type: 'string' },
      slug: { type: 'string' },
      status: { type: 'string' },
      logo_url: { type: 'string', nullable: true },
      contact_email: { type: 'string', format: 'email', nullable: true },
      contact_phone: { type: 'string', nullable: true },
      address: { type: 'string', nullable: true },
      social_links: {
        type: 'object',
        additionalProperties: { type: 'string' },
        nullable: true,
      },
    },
    required: ['name', 'slug', 'status'],
  },
  StudioPublicClient: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      name: { type: 'string' },
      slug: { type: 'string' },
      event_date: { type: 'string', format: 'date', nullable: true },
      status: { type: 'string' },
      subheading: { type: 'string', nullable: true },
      header_media_url: { type: 'string', nullable: true },
      header_media_type: { type: 'string', nullable: true },
      photo_count: { type: 'number' },
    },
    required: ['id', 'name', 'slug'],
  },
} as const;
